name: CI/CD Pipeline

on:
    push:
        branches:
            - main

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.11"

            - name: Cache pip dependencies
              uses: actions/cache@v3
              with:
                  path: ~/.cache/pip
                  key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
                  restore-keys: |
                      ${{ runner.os }}-pip-

            - name: Install dependencies
              run: |
                  pip install -r requirements.txt
                  pip install pytest pytest-cov pytest-asyncio httpx

            - name: Run unit tests
              run: |
                  pytest tests/ -v

            - name: Run linting
              run: |
                  pip install flake8 black isort
                  flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                  black --check .
                  isort --check-only .

    # build:
    #     runs-on: ubuntu-latest
    #     needs: test

    #     steps:
    #         - name: Checkout code
    #           uses: actions/checkout@v4

    #         - name: Set up Docker Buildx
    #           uses: docker/setup-buildx-action@v2

    #         - name: Log in to Docker Hub
    #           uses: docker/login-action@v2
    #           with:
    #               username: ${{ secrets.DOCKER_USERNAME }}
    #               password: ${{ secrets.DOCKER_PASSWORD }}

    #         - name: Build and push Docker image
    #           uses: docker/build-push-action@v4
    #           with:
    #               context: .
    #               push: true
    #               tags: minhtai03/meowchat:latest

    # Commented out original deployment code for reference
    # deploy:
    #     runs-on: ubuntu-latest
    #     needs: build
    #     steps:
    #         - name: Deploy to VPS
    #           uses: appleboy/ssh-action@v0.1.5
    #           with:
    #               host: ${{ secrets.VPS_HOST }}
    #               username: ${{ secrets.VPS_USERNAME }}
    #               key: ${{ secrets.VPS_SSH_KEY }}
    #               port: ${{ secrets.VPS_PORT }}
    #               script: |
    #                   sudo docker pull minhtai03/meowchat:latest
    #                   sudo docker stop meowchat_flask_container || true
    #                   sudo docker rm meowchat_flask_container || true
    #                   sudo docker run --env-file .env -d -p 5000:5000 --name meowchat_flask_container --restart unless-stopped minhtai03/meowchat:latest
